server/maaps/urls.py
from django.contrib import admin

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import maaps.views as views

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', views.index, name='index'),

    # Point of sale
    path(r'pos/'           , views.pos__index      , name='pos__index'),
    path(r'pos/login_user' , views.pos__login_user , name='pos__login_user'),
    path(r'pos/logout', views.pos__logout_staff, name='pos__logout'),
    #path(r'pos/deposit'    , views.pos__deposit    , name='pos__deposit'),
    path(r'pos/payment'    , views.pos__payment    , name='pos__payment'),
    path(r'pos/write_card' , views.pos__write_card , name='pos__write_card'),
    path(r'pos/info'       , views.pos__info       , name='pos__info'),
    path(r'pos/login_staff', views.pos__login_staff, name='pos__login_staff'),
    path(r'pos/login_staff/<user_token>', views.pos__login_staff, name='pos__login_staff_with_parameter'),
    path(r'pos/login_user', views.pos__login_user, name='pos__login_user'),
    path(r'pos/login_user/<user_token>', views.pos__login_user, name='pos__login_user_with_parameter'),

                  # Machine
    path(r'machine/'                            , views.machine__login_machine    , name='machine__login'),
    path(r'machine/logout'                      , views.machine__logout_machine   , name='machine__logout'),
    path(r'machine/show_session'                , views.machine__show_session     , name='machine__show_session'),
    path(r'machine/login_user'                  , views.machine__login_user       , name='machine__login_user'),
    path(r'machine/login_user/<user_token>'     , views.machine__login_user       , name='machine__login_user_with_parameter'),
    path(r'machine/logout_user'                 , views.machine__logout_user      , name='machine__logout_user'),
    path(r'machine/pay_material'                , views.machine__pay_material     , name='machine__pay_material'),
    path(r'machine/pay_material/<user_token>'   , views.machine__pay_material     , name='machine__pay_material_with_parameter'),
    path(r'machine/rate_machine'                , views.machine__rate_machine     , name='machine__rate_machine'),
    path(r'machine/tutor_required'              , views.machine__tutor_required   , name='machine__tutor_required'),
    path(r'machine/payment_required'            , views.machine__payment_required , name='machine__payment_required'),
    path(r'machine/other_user_pays'             , views.machine__other_user_pays  , name='machine__payment_other_user_pays'),
    path(r'machine/other_user_pays/<user_token>', views.machine__other_user_pays  , name='machine__payment_other_user_pays_with_parameter'),
    path(r'machine/auto_logout'                 , views.machine__auto_logout      , name='machine__auto_logout'),
    path(r'machine/M:<machine_token>'           , views.machine__login_machine    , name='machine__login_with_parameter'),

    # Webinterface
    path('webif/'                               , views.webif__dashboard   , name='webif__dashboard'),
    path('webif/info'                           , views.webif__info        , name='webif__info'),
    path('webif/prices'                         , views.webif__prices        , name='webif__prices'),
    path('webif/agb'                            , views.webif__agb        , name='webif__agb'),
    path('webif/contract'                       , views.webif__contract        , name='webif__contract'),
    path('webif/contract_paypal'                       , views.webif__contract_paypal        , name='webif__contract_paypal'),
    path('webif/session/end/<int:session_id>'   , views.webif__session_end , name='webif__session_end'),
    path('webif/spaceaccesstracking/end/<int:spaceaccesstracking_id>'   , views.webif__spaceaccesstracking_end , name='webif__spaceaccesstracking_end'),
    path('webif/user/list'                      , views.webif__user__list  , name='webif__user__list'),
    path('webif/user/create'                    , views.webif__user__create, name='webif__user__create'),
    path('webif/user/show/<int:user_id>'        , views.webif__user__show  , name='webif__user__show'),
    path('webif/user/update/<int:user_id>'      , views.webif__user__update, name='webif__user__update'),
    path('webif/user/delete/<int:user_id>'      , views.webif__user__delete, name='webif__user__delete'),
    path('webif/user/deposit/<int:profile_id>'     , views.webif__user__deposit, name='webif__user__deposit'),
    path('webif/user/contract/<int:user_id>'        , views.webif__user__contract, name='webif__user__contract'),
    path('webif/user/contract_sepa/<int:user_id>'        , views.webif__user__contract_sepa, name='webif__user__contract_sepa'),
    path('webif/user/contract_paypal/<int:user_id>'        , views.webif__user__contract_paypal, name='webif__user__contract_paypal'),
    path('webif/user/create_new_card/<int:user_id>'  , views.webif__user__create_new_card, name='webif__user__create_new_card'),

    path('webif/invoice/list'                 , views.webif__invoice__list, name='webif__invoice__list'),
    path('webif/invoice/show/<int:invoice_id>', views.webif__invoice__show, name='webif__invoice__show'),
    path('webif/invoice/list_createable'      , views.webif__invoice__list_createable, name='webif__invoice__list_createable'),
    path('webif/invoice/create/<int:user_id>' , views.webif__invoice__create, name='webif__invoice__create'),

      ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/maaps/models.py
import itertools
import math
import os
import uuid
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.utils.timezone import now
from django_resized import ResizedImageField
from django.utils import timezone
from unidecode import unidecode


#
# HELPER FUNCTIONS
#
def rename_file(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}_{}.{}'.format(instance.user.username, now().strftime('%Y.%m.%d_%H.%M.%S'), ext)
    return os.path.join('photos/', filename)



#
# ENUMS
#
class SpaceRentPaymentType:
    monthly = "monthly"
    daily = "daily"

class TransactionType:
    from_cash_for_deposit = "from_cash_for_deposit"
    from_cash_for_invoice = "from_cash_for_invoice"
    from_cash_for_rent = "from_cash_for_rent"
    from_bank_for_deposit = "from_bank_for_deposit"
    from_bank_for_invoice = "from_bank_for_invoice"
    from_bank_for_rent = "from_bank_for_rent"
    from_deposit_for_machine = "from_deposit_for_machine"
    from_deposit_for_material = "from_deposit_for_material"
    from_deposit_for_rent = "from_deposit_for_rent"
    virtual_for_deposit = "virtual_for_deposit"

class InvoiceType:
    receipt = "receipt"
    invoice = "invoice"
    virtual = "virtual"


#
# OTHER
#
class Price (models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    identifier = models.CharField(max_length=100, blank=True)
    discount = models.FloatField(default=0)
    members = models.FloatField(default=0)
    default = models.FloatField(default=0)
    commercial = models.FloatField(default=0)

    def __str__(self):
        return "%s: %s, %s, %s" % (self.identifier, self.discount, self.default, self.commercial)

class Token(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    identifier = models.CharField(max_length=48, blank=True)
    enabled = models.BooleanField(default=False)
    can_write = models.BooleanField(default=False)  # true if terminal should show token to be written to rfid card
    profile = models.ForeignKey("Profile", related_name="tokens", on_delete=models.CASCADE, blank=True, null=True)
    machine = models.ForeignKey("Machine", related_name="tokens", on_delete=models.CASCADE, blank=True, null=True)

class SpaceAccessTracking(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="spaceAccessTrackings", verbose_name='Benutzer')
    start = models.DateTimeField(blank=True, null=True)
    end = models.DateTimeField(blank=True, null=True)
    spaceRentPayment = models.ForeignKey("SpaceRentPayment", on_delete=models.SET_NULL, blank=True, null=True, related_name="spaceAccessTrackings")



#
# PROFILE
#
class Profile(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # USER DATA
    profile_picture = ResizedImageField(blank=True, null=True, upload_to=rename_file)
    birthdate = models.DateField(blank=True, null=True, default=None)
    company_name = models.CharField(max_length=200, blank=True, default="")

    #PAYMENT
    paying_user = models.ForeignKey("Profile", on_delete=models.CASCADE, blank=True, null=True)
    allow_postpaid = models.BooleanField(default=False)
    commercial_account = models.BooleanField(default=False)  # == mit mwst
    discount_account = models.BooleanField(default=False)  # z.b. < 16 Jahre
    monthly_payment = models.BooleanField(default=False)  # monatlich oder tagesaccount
    prepaid_deposit = models.FloatField(default=0)

    # ADDRESS
    street = models.CharField(max_length=200, blank=True, default="")
    postalcode = models.CharField(max_length=200, default="", blank=True)
    city = models.CharField(max_length=200, blank=True, default="")

    def __str__(self):
        if self.company_name != "":
            return "%s, %s. %s" % (self.company_name, self.user.first_name[0].upper(), self.user.last_name)
        return "%s %s" % (self.user.first_name, self.user.last_name)

    def get_current_token(self):
        tokens = Token.objects.filter(enabled=True, profile=self)
        if len(tokens) == 0:
            return None
        return tokens[0]

    def is_underage(self):
        if self.birthdate is None:
            return False
        return timezone.now().date() - self.birthdate < timedelta(days=365*18)

    def get_paying_user(self):
        if self.paying_user is None:
            return self
        return self.paying_user



#
# MACHINE
#
class Machine(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=200)
    group_name = models.CharField(max_length=100, blank=True)
    comment = models.CharField(max_length=10000, blank=True)
    ask_clean = models.BooleanField(default=False)
    ask_pay_material = models.BooleanField(default=False)
    show_autologout = models.BooleanField(default=False)
    price_per_hour = models.ForeignKey(Price, on_delete=models.SET_NULL, related_name="machinePerHour", blank=True, null=True)  # in Euro
    price_per_usage = models.ForeignKey(Price, on_delete=models.SET_NULL, related_name="machinePerUsage", blank=True, null=True)  # in Euro
    tutor_required_count = models.IntegerField(default=0)  # wir oft
    tutor_required_once_after_month = models.IntegerField(default=24)  # all
    current_session = models.OneToOneField("MachineSession", on_delete=models.SET_NULL, related_name="current_session", blank=True, null=True)
    allowed_users = models.ManyToManyField(User, related_name="allowed_machines")

    def __str__(self):
        return "%s" % self.name

    def user_is_allowed(self, user):
        return (user in self.allowed_users.all()) or user.is_staff

    def user_requires_tutor(self, user):
        if user.is_staff: return False
        return self.tutor_required_count > self.count_usages(user)

    def user_requires_tutor_once(self, user):
        if user.is_staff: return False
        if self.count_usages(user) > 0:
            nr_of_latest_sessions = MachineSession.objects.filter(~Q(start=None), ~Q(end=None), machine__group_name=self.group_name, user=user, end__gt=now() - timedelta(days=31 * self.tutor_required_once_after_month)).count()
            if nr_of_latest_sessions == 0:
                return True
        return False

    def user_can_tutor(self, tutor):
        if tutor.is_staff: return True
        return self.user_requires_tutor(tutor) is False and self.user_requires_tutor_once(tutor) is False

    def count_usages(self, user):
        qs = MachineSession.objects.filter(~Q(start=None), ~Q(end=None), machine__group_name=self.group_name, user=user).values('created')
        grouped = itertools.groupby(qs, lambda d: d.get('created').strftime('%Y-%m-%d'))
        return len([ True for _, _ in grouped])

    def get_price(self, paying_user_profile):
        price_per_usage, price_per_hour = 0, 0
        if paying_user_profile.commercial_account:
            if self.price_per_hour  is not None : price_per_hour = self.price_per_hour.commercial
            if self.price_per_usage is not None : price_per_usage = self.price_per_usage.commercial
        elif paying_user_profile.discount_account:  # discount account
            if self.price_per_hour  is not None: price_per_hour = self.price_per_hour.discount
            if self.price_per_usage is not None: price_per_usage = self.price_per_usage.discount
        elif paying_user_profile.monthly_payment:  # membership
            if self.price_per_hour  is not None: price_per_hour = self.price_per_hour.members
            if self.price_per_usage is not None: price_per_usage = self.price_per_usage.members
        else:
            if self.price_per_hour  is not None: price_per_hour = self.price_per_hour.default
            if self.price_per_usage is not None: price_per_usage = self.price_per_usage.default
        return price_per_usage, price_per_hour

    def requires_payment(self, paying_user_profile):
        price_per_usage, price_per_hour = self.get_price(paying_user_profile)
        return price_per_usage > 0 or price_per_hour > 0

class MachineSession(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="MachineSessionsUser")
    tutor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="MachineSessionsTutor", blank=True, null=True)
    autologout_at = models.DateTimeField(default=None, blank=True, null=True)
    start = models.DateTimeField(default=None, blank=True, null=True)
    end = models.DateTimeField(default=None, blank=True, null=True)
    comment = models.CharField(max_length=10000, blank=True)
    rating_clean = models.IntegerField(default=-1)

    @property
    def autologout_timediff(self):
        if self.autologout_at is not None:
            timediff_total_minutes = int(math.ceil((self.autologout_at - now()).total_seconds() / 60))
            timediff_minutes = timediff_total_minutes % 60
            timediff_hours = int((timediff_total_minutes - timediff_minutes) / 60)
            return timediff_total_minutes, timediff_hours, timediff_minutes

    def __str__(self):
        return "%s;%s" % (self.machine.name, self.start)



#
# PAYED ACTIONS
#
class MachineSessionPayment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

server/maaps/forms.py
from django.forms import ModelForm

from .models import Profile


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

server/maaps/views/index.py
from django.http import HttpResponse
from django.template import loader


def index(request):
    return HttpResponse(loader.get_template('index.html').render({}, request))

server/maaps/templates/webif/user/create.html
{% extends "webif/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/webif">Makerhafen</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/list">Benutzer</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/create">Erstellen</a></li>
        </ol>
    </nav>
    <!-- /Breadcrumb -->
    {% if last_error != None %}
        <div class="row">
            <div class="col-md-12 ">
                <b>Fehler:</b><br>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h5>Neuen Benutzer anlegen</h5>
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <h4>Maschinen Zugriff</h4>
                {% for machine in machines %}
                    <input type="checkbox" name="allowed_machines" value="{{ machine.id }}"  {% if profile.user in machine.allowed_users.all %}checked{% endif %}> {{ machine }}<br>
                {% endfor %}
                {% include "webif/user/get_picture.html" %}
                <br>
                <br>
                <a type="button" class="btn btn-danger" href="{%url 'webif__user__list' %}">Abbrechen</a>
                <button type="submit" class="btn btn-success">Erstellen</button>
            </form>
        </div>
    </div>

{% endblock %}

server/maaps/templates/webif/user/deposit.html
{% extends "webif/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <style>
        td {
            text-align: center;
            white-space: nowrap;
        }
        th {
            text-align: center;
        }
    </style>
    <nav aria-label="breadcrumb" class="main-breadcrumb hidden-print">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/webif">Makerhafen</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/list">Benutzer</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/show/{{profile.id}}">{{profile}}</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/show/{{profile.id}}">Einzahlung Buchen</a></li>
        </ol>
    </nav>
    <br>
    <br>
    <div class="row">
        <div class="col-12" style="text-align:center">
            <form id="form" method="post">
                {% csrf_token %}
                <label>
                    Betrag
                    <input id="deposit_value" name="deposit_value" type="number">
                </label>
                <br>
                <br>
                <div>
                  <input type="radio" id="type_1"  name="type" value="from_cash_for_deposit" checked>
                  <label for="type_1">Bargeld Einzahlung für Prepaid Guthaben </label>
                </div>

                {% if profile.monthly_payment %}
                    <div>
                      <input type="radio" id="type_2" name="type" value="from_cash_for_rent">
                      <label for="type_2">Bargeld Einzahlung für Monatsbeitrag</label>
                    </div>

                    <div>
                      <input type="radio" id="type_3" name="type" value="from_bank_for_rent">
                      <label for="type_3">Überweisung für Monatsbeitrag</label>
                    </div>
                {% endif %}

                <div>
                  <input type="radio" id="type_4" name="type" value="from_bank_for_deposit">
                  <label for="type_4">Überweisung für Prepaid Guthaben</label>
                </div>
                <div>
                  <input type="radio" id="type_5" name="type" value="virtual_for_deposit">
                  <label for="type_4">Virtuelles Guthaben</label>
                </div>

                <button class="btn" type="submit">Buchen</button>
            </form>
        </div>



    </div>

    <br>
    <br>


    {% if last_error != None %}
        <div class="row">
            <div class="col-xs-12 ">
                <b>Fehler:</b><br>
            </div>
        </div>
    {% endif %}



{% endblock %}

server/maaps/templates/webif/user/get_picture.html
<input hidden type="text" id = "image_data" name="image_data" value="">
<div class="row">
    <div class="col-md-6">
        <video style="width:100%" id="player" controls autoplay></video>
    </div>
    <div class="col-md-6" style="">
        <canvas width=1280 height=960 style="width:100%;height:100%" id="canvas"></canvas>
    </div>
    <div class="col-md-12">
        <button type="button" class="btn btn-success" id="capture">Foto machen</button>
    </div>
</div>

<script>
    const player = document.getElementById('player');
    const canvas = document.getElementById('canvas');
    const context = canvas.getContext('2d');
    const captureButton = document.getElementById('capture');

    const constraints = { video: true, };

    captureButton.addEventListener('click', () => {
        context.drawImage(player, 0, 0, canvas.width, canvas.height);
        var url = canvas.toDataURL();
        document.getElementById("image_data").value = url;
    });

    navigator.mediaDevices.getUserMedia(constraints).then((stream) => {
        player.srcObject = stream;
    });
</script>

server/maaps/templates/webif/user/list.html
{% extends "webif/base.html" %}

{% block content %}
    <!-- Breadcrumb -->
    <nav aria-label="breadcrumb" class="main-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/webif">Makerhafen</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/list">Benutzer</a></li>
        </ol>
    </nav>
    <!-- /Breadcrumb -->
    <br>
    <div class="row">
        <div class="col-md-8"><h4>Profile List</h4></div>
        <div class="col-md-4" style="text-align:right"><a type="button" class="btn btn-success" href="{%url 'webif__user__create' %}">Neuen Nutzer stellen</a></div>
    </div>

    <br>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Vorname</th>
                    <th scope="col">Nachname</th>
                    <th scope="col">Firma</th>
                    <th scope="col">Email</th>
                    <th scope="col">Guthaben (Euro)</th>
                    <th scope="col">Auf Rechnung</th>
                    <th scope="col">Kommerziell</th>
                    <th scope="col">Ermäßigt</th>
                    <th scope="col">Jemand anderes zahlt</th>
                    <th scope="col">Tages/Monats Benutzer</th>
                    <th scope="col">Bild</th>
                </tr>
                </thead>
                <tbody>
                {% for profile in profiles %}
                    <tr>
                        <td>{{ profile.user.first_name }}</td>
                        <td>{{ profile.user.last_name }}</td>
                        <td>{{ profile.company_name }}</td>
                        <td>{{ profile.user.email }}</td>
                        {% if profile.paying_user %}
                            <td {% if profile.paying_user.prepaid_deposit < 0 %}style="color:red"{% endif %}>{{ profile.paying_user.prepaid_deposit }}</td>
                        {% else %}
                            <td {% if profile.prepaid_deposit < 0 %}style="color:red"{% endif %}>{{ profile.prepaid_deposit }}</td>
                        {% endif %}
                        <td>
                            {% if profile.paying_user %}

                                {% if profile.paying_user.allow_postpaid %}{{ profile.paying_user }}, Ja{% else %}{% endif %}
                            {% else %}
                                {% if profile.allow_postpaid %}Ja{% else %}{% endif %}
                            {% endif %}
                        </td>
                        <td>
                            {% if profile.paying_user %}
                                {% if profile.commercial_account %}{{ profile.paying_user }}, Ja{% else %}{% endif %}
                            {% else %}
                                {% if profile.commercial_account %}Ja{% else %}{% endif %}
                            {% endif %}
                        </td>
                        <td>
                            {% if profile.paying_user %}
                                {% if profile.discount_account %}{{ profile.discount_account }}, Ja{% else %}{% endif %}
                            {% else %}
                                {% if profile.discount_account %}Ja{% else %}{% endif %}
                            {% endif %}
                        </td>
                        <td>{% if profile.paying_user %}{{profile.paying_user }}{% else %}{% endif %}</td>
                        <td>
                            {% if profile.paying_user %}
                                {{ profile.paying_user }},
                                {% if profile.paying_user.monthly_payment %}Monatlich{% else %}Tagesbenutzer{% endif %}
                            {% else %}
                                {% if profile.monthly_payment %}Monatlich{% else %}Tagesbenutzer{% endif %}
                            {% endif %}

                        </td>
                        <td>
                            {% if profile.profile_picture %}<img style="width:50px" src = "{{ profile.profile_picture.url }}"/>{% endif %}
                        </td>
                        <td>
                            <a type="button" class="btn btn-success" href="/webif/user/show/{{ profile.id }}">Anzeigen</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

server/maaps/templates/webif/user/update.html
{% extends "webif/base.html" %}
{% load crispy_forms_tags %}

{% block content %}


    <nav aria-label="breadcrumb" class="main-breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/webif">Makerhafen</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/list">Benutzer</a></li>
            <li class="breadcrumb-item"><a href="/webif/user/show/{{profile.id}}">{{profile}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Bearbeiten</li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-6 col-md-offset-2"><h4>Benutzer <b>{{profile}}</b> aktualisieren</h4></div>
        <div class="col-md-3 ">
            {% if profile.profile_picture %}
            <img style="width:110px" src = "{{ profile.profile_picture.url }}"/>
            {% endif %}
        </div>
    </div>

    {% if last_error != None %}
        <div class="row">
            <div class="col-md-12 ">
                <b>Fehler:</b><br>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <h4>Maschinen Zugriff</h4>
                {% for machine in machines %}
                <input type="checkbox" name="allowed_machines" value="{{ machine.id }}"  {% if profile.user in machine.allowed_users.all %}checked{% endif %}> {{ machine }}<br>
                {% endfor %}
                <h4>Foto</h4>
                {% include "webif/user/get_picture.html" %}
                <br>
                <br>
                <a type="button" class="btn btn-danger" href="{%url 'webif__user__list' %}">Cancel</a>
                <button type="submit" class="btn btn-success">Update</button>
            </form>
        </div>
    </div>
    <script>
          $( function() {
        $( "#id_birthdate" ).datepicker();
      } );

    </script>
{% endblock %}